cask_args appdir: '/Applications'

tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "romkatv/powerlevel10k"

brew "awsume"
brew "bitwarden-cli"
brew "curl"
brew "chezmoi"
brew "dive"
brew "git"
brew "jq"
brew "node"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "terraform"
brew "terragrunt"
brew "terrascan"
brew "tflint"
brew "wget"
brew "yamllint"
brew "yarn"
brew "ykman"
brew "zsh"

cask "bitwarden"
cask "docker"
cask "kitty"
cask "rectangle"
cask "stats"
cask "tunnelblick"
cask "visual-studio-code"
