#!/usr/bin/env bash

# ~/.macos - inspired by https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overrding
# settings we're about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished

###############################################################################
# General UI/UX                                                               #
###############################################################################




# Put the Dock on the bottom of the screen.
defaults write com.apple.dock "orientation" -string "bottom"

# Set the icon size of Dock items in pixels.
defaults write com.apple.dock "tilesize" -int "42"

# Autohide the Dock.
defaults write com.apple.dock "autohide" -bool "true"

# Remove the auto-hiding Dock delay.
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when  hiding/showing the Dock.
defaults write com.apple.dock autohide-time-modifier -float 0

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

##############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                #
##############################################################################

# Disable press-and-hold for keys in favor of key repeat.
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate.
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Set language and text formats.
defaults write NSGlobalDomain AppleLanguages -array "en" "pl"
defaults write NSGlobalDomain AppleLocale -string "en_US@currency=PLN"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
sudo systemsetup -settimezone "Europe/Warsaw" > /dev/null 2> /dev/null

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Dock"; do
	killall "${app}" &> /dev/null
done
